name: CI CD

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

env:
  DOTNET_VERSION: 5.0.101
  CONFIGURATION: Release

jobs:
  build-test:    
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore    
    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }}

  github-nuget-deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and create nuget package
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore    
    - name: Push nuget package
      run: dotnet nuget push "src/GitHubPackageNuget.Lib/bin/Release/GitHubPackageNuget.Lib.1.1.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Arnab-Developer/index.json --skip-duplicate

  nuget-org-deploy:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and create nuget package
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore    
    - name: Push nuget package
      run: dotnet nuget push "src/GitHubPackageNuget.Lib/bin/Release/GitHubPackageNuget.Lib.1.1.0.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate